### ISSUE TITLE
template missing: parameterized dataset excel import

### ISSUE THREAD

**Issue by simb-sdu** [brightway-lca/brightway2-io#123]
Hi, i am trying to follow the [notebook](https://github.com/brightway-lca/brightway2/blob/master/notebooks/Parameters%20-%20Excel%20import.ipynb) to import parameterized dataset from excel

however the link to the [parameterized template](https://bitbucket.org/cmutel/brightway2-io/raw/default/tests/fixtures/excel/sample_activities_with_variables.xlsx) is broken. 
@cmutel is the file accessible anyhow?

**Comment by simb-sdu** [comment]
Or is there perhaps a better way to migrate my LCA model from OpenLCA to Brightway2?

**Comment by cmutel** [comment]
Dear @simb-sdu 

Thanks for the bug report. We moved off bitbucket a long time ago, it is frustrating that these zombie links are still around. Sorry!

You can find all the example templates here: https://github.com/brightway-lca/brightway2-io/tree/master/tests/fixtures/excel. I will update the notebook.

We have an experimental OpenLCA reader, but it doesn't support parameterization and is still under development.

**Comment by cmutel** [comment]
Fixed in https://github.com/brightway-lca/brightway2/commit/4db507f6a05276c4fd68adaa0690c2a36ef3b42a

**Comment by simb-sdu** [comment]
Hi @cmutel 
Thank you for the quick reply and direction to the new location.

I suppose that the best way to migrate from olca is then to export the processes to excel and import the parametrized datasets to bw2. I plan continue the work on this LCA in aActivity Browser. Can you confirm if this will work?

Edit: seems like it will be much more simple to manually re-create all processes
