### ISSUE TITLE
A question: possibility to get life cycle costing information from openLCA?

### ISSUE THREAD

**Issue by junseokkim93** [brightway-lca/brightway2-io#144]
Hello,

First of all my apology if this is wrong place to put a question like this.
This is my first time writing a post in GitHub.

As I understand, Brightway2 does not provide cost information in process flows, and I found out that OpenLCA is capable of providing that information.

My question is if I can import that information to my python script somehow (because I have seen that there was python interpreter implemented in openLCA?)

Do you guys know if this is feasible and if so, could you briefly explain how I can achieve that? I’ve been exploring internet searching for the information but it wasn’t successful.

Thank you in advance : )

**Comment by mfastudillo** [comment]
Brightway is an LCA framework, not a source of data. Depending on the database you are using (ecoinvent, exiobase ...) it will have value added elementary flows or not. The default database of elementary flows used by Brightway contains all the components of value added e.g. `bw2data.Database('biosphere3').search('economic')` which is what you need to compute life cycle costing calculations. As the question about how to extract that data from openLCA ... I would ask in openLCA forums

**Comment by tngTUDOR** [comment]
Thanks @mfastudillo  for the answer. I think it is clear.
