### ISSUE TITLE
Import Agribalyse3.1.bw2package in Brightway failed. OSError: Invalid data stream

### ISSUE THREAD

**Issue by R-Hammer** [brightway-lca/brightway2-io#148]
I am new to brightway and looking for help. The error I got is "OSError: Invalid data stream" when importing the new Agribalyse3.1. Data: https://doc.agribalyse.fr/documentation-en/agribalyse-data/data-access

Previously I imported ecoinvent3.9 with no errors. I followed these instructions: https://github.com/sc-gcoste/brightway-agribalyse3.1/blob/master/exploring_agb3.1.ipynb

Where is my error?

```
import brightway2 as bw
import os

bw.projects.set_current('Importing agribalyse3.1')
bw.bw2setup()
print(os.listdir('../data/'))
path ='../data/AGB31.bw2package'
bw.BW2Package.import_file(path)
```

Output:

```
Biosphere database already present!!! No setup is needed
['AGB31.bw2package']
Output exceeds the size limit. Open the full output data in a text editor
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
Cell In [5], line 4
      2 print(os.listdir('../data/'))
      3 path ='../data/AGB31.bw2package'
----> 4 bw.BW2Package.import_file(path)

File c:\Users\Pro\anaconda3\envs\ab_dev\lib\site-packages\bw2io\package.py:198, in BW2Package.import_file(cls, filepath, whitelist)
    186 @classmethod
    187 def import_file(cls, filepath, whitelist=True):
    188     """Import bw2package file, and create the loaded objects, including registering, writing, and processing the created objects.
    189 
    190     Args:
   (...)
    196 
    197     """
--> 198     loaded = cls.load_file(filepath, whitelist)
    199     with warnings.catch_warnings():
    200         warnings.simplefilter("ignore")

File c:\Users\Pro\anaconda3\envs\ab_dev\lib\site-packages\bw2io\package.py:180, in BW2Package.load_file(cls, filepath, whitelist)
    168 @classmethod
    169 def load_file(cls, filepath, whitelist=True):
    170     """Load a bw2package file with one or more objects. Does not create new objects.
    171 
...
--> 103     data = self._decompressor.decompress(rawblock, size)
    104 if data:
    105     break

OSError: Invalid data stream
```

**Comment by cmutel** [comment]
This doesn't seem to be a fixable error, the file `AGB31.bw2package` is broken. It needs to be regenerated - or, better, you should skip the `BW2Package` completely and import the data directly from the sources.

**Comment by R-Hammer** [comment]
Thank you, for your answer. 
What do you mean by “data directly from the sources”? I thought the bw2package form the original website is the source.

**Comment by cmutel** [comment]
The original data should be provided in XML or CSV, especially as you seem
not to be able to load the .bw2package (even if it comes from the original
source :)

**Comment by sc-gcoste** [comment]
@R-Hammer, the file you are trying to import has been created with `bw2io == 0.8.7`, and I think that's why you didn't manage to import it. I made a test with a fresh install of brightway with `bw2io == 0.8.7` and I ran you script with no error.
See [here](https://github.com/brightway-lca/brightway2-io#compatibility-with-brightway2x) for more information on `bw2io` versions.

**Comment by GreLeBr** [comment]
@sc-gcoste Thanks for the answer, I wanted to ask you exactly the same question.  
It indeed worked for me after forcing bw2io 0.8.7, it still needs almost 30gb of ram to load the file.

**Comment by sc-gcoste** [comment]
Yes, the resource consumption of the import is quite big. I don't have 30gb of ram on my computer but still managed to import it. It just takes a while.

**Comment by sc-gcoste** [comment]
In any case, I also added a link to the original .csv file on the [repository](https://github.com/sc-gcoste/brightway-agribalyse3.1/blob/master/README.md).

**Comment by GreLeBr** [comment]
Thanks, I would have said this must be much easier to manipulate but that csv file is something else or I am missing something.   
It seems like it is text mixed with data with no structure to it. Is there like a way to open that properly?

**Comment by sc-gcoste** [comment]
It is a SimaPro .csv export. I agree that's a terrible way of formatting data but that's the only way to import/export data from SimaPro to Brightway

**Comment by R-Hammer** [comment]
I ran it again on my windows pc with the following packages and Python 3.13.9. 
```
pip install brightway2
pip install bw2io==0.8.7
pip install pywin32
```
and checked the versions to be sure:
```
print('io version: ', bw2io.__version__)
print('bw version: ', bw.__version__)

##### output:
io version: (0, 8, 7) 
bw version: (2, 4, 1)
```
unfortunately i got the same error

A friend tried it on her MacBook Air M1 and got the same error.
Could anything else with my setting be wrong or so some of you have an other version of the bw2package of the agribalyse data?

However, with the SimaPro CSV the import worked. Thanks a lot!
