### ISSUE TITLE
Unlinked exchanged importing Ecoinvent 3.8 

### ISSUE THREAD

**Issue by lea-we** [brightway-lca/brightway2-io#151]
Hello, beginner here, so please excuse any superfluous questions:

I wanted to install my ecoinvent 3.8 through jupyter notebook:
`if 'ecoinvent 3.8-cutoff-ecoSpold02' in bw.databases:
    print("Database has already been imported.")
else: 
    fpei38cut = r"C:\Users\lea\Documents\Master\MA_30\Modell\ecoinvent\ecoinvent 3.8_cutoff_ecoSpold02\datasets"
    ei38cut = bw.SingleOutputEcospold2Importer(fpei38cut, 'ecoinvent 3.8-cutoff_ecoSpold02')
    ei38cut
    ei38cut.apply_strategies()
    ei38cut.statistics()`
I got an error of unlinked exchanges:

> 19565 datasets 
629959 exchanges 
1655 unlinked exchanges 
Type biosphere: 15 unique unlinked exchanges.< 

I found the solution of `ei38cutoff.drop_unlinked(i_am_reckless=True)` which I have applied, but now I can't seem to import any data through excel without getting errors.

I have generated the unlinked elements and, since I want to do an LCA about steel, I don't think dropping iron out would work for me:
<img width="576" alt="image" src="https://user-images.githubusercontent.com/120476673/209850230-43c78eb9-ffe9-41a3-9a89-9d4269595201.png">
Versions I am using:
python                    3.8.15
numpy                     1.21.0
bw2io                     0.8.8
brightway2                2.4.2

I would be greatful for any advice as how to solve this. Thanks!

**Comment by lelecanfora** [comment]
Same error here with a brand new "ecoinvent 3.8_cutoff_ecoSpold02.7z" downloaded from the Ecoinvent website:

```
if not bd.databases.get('ei38cutoff'):
    ei38cutoff = bi.SingleOutputEcospold2Importer(
        os.path.join(ecospold_dir, 'datasets'),
        "ei38cutoff" # new db name is defined here
    )
    ei38cutoff.apply_strategies()
    ei38cutoff.statistics()
    ei38cutoff.write_database()
```

ERROR InvalidExchange


Packages
brightway25               1.0.6                     py_10    cmutel
bw2calc                   2.0.dev12                  py_0    cmutel
bw2data                   4.0.dev18                  py_0    cmutel
bw2io                     0.9.dev10                  py_0    cmutel

**Comment by HaSchneider** [comment]
Check the readme of the package: https://github.com/brightway-lca/brightway2-io
For importing ecoinvent 3.8 in a brightway2.5 project, you need bw2io 0.9.dev11.

`pip install bw2io==0.9.dev11
`

And you have to use this version as well to setup your project before importing ecoinvent 3.8.
 
`bw2io.bw2setup()`

I hope this helps.

**Comment by bernardomendonca** [comment]
Unfortunately I'm getting the same issue when running:

```
if 'ecoinvent 3.8 cutoff' in bi.databases:
    print("Database has already been imported")
else:
    ei38 = bi.SingleOutputEcospold2Importer(ei38cutoffdir, 'ecoinvent 3.8 cutoff') # You can give it another name of course
    ei38.apply_strategies()
    ei38.statistics()
    ei38.drop_unlinked(True)
    ei38.write_database() # This will take some time.
```

> 19565 datasets
> 629959 exchanges
> 1655 unlinked exchanges
>   Type biosphere: 15 unique unlinked exchanges

I'm trying to use premise, and when performing the transformation afterwards I keep getting invalid exchanges.

I would like to import ecoinvent 3.8 cutoff without having to use ei38.drop_unlinked(True)

Has anyone managed to figure out the issue?

My versions:
brightway25               1.0.6                    pypi_0    pypi
bw2calc                   2.0.dev16                pypi_0    pypi
bw2data                   4.0.dev33                pypi_0    pypi
bw2io                     0.9.dev26                pypi_0    pypi

Thanks :)

**Comment by cmutel** [comment]
`bw2io` comes with a fixes set of biosphere flows from ecoinvent, and the `bw2io` version you have is for ecoinvent 3.9 or 3.10. So you need a new set of flows. Luckily, there is a better way :)

You can use [import_ecoinvent_release](https://github.com/brightway-lca/brightway2-io/blob/main/bw2io/ecoinvent.py#L55) to get any ecoinvent version back to 3.4, including its biosphere flows and LCIA implementation. Please read the docs to avoid frustration as this flexibility means some Brightway patterns needed to change.

**Comment by OliverLyon** [comment]
> Check the readme of the package: https://github.com/brightway-lca/brightway2-io For importing ecoinvent 3.8 in a brightway2.5 project, you need bw2io 0.9.dev11.
> 
> `pip install bw2io==0.9.dev11 `
> 
> And you have to use this version as well to setup your project before importing ecoinvent 3.8.
> 
> `bw2io.bw2setup()`
> 
> I hope this helps.

I got the same issue for 3.7.1 cutoff, do you know which version of bw2io would fit this database? Thanks
