### ISSUE TITLE
New units in ei39 missed by bw2io

### ISSUE THREAD

**Issue by romainsacchi** [brightway-lca/brightway2-io#173]
I believe there are new units in ei39 (e.g., "Sm3", "kg*day") which are not cleaned/normalized by `bw2io 0.8.8`.
Not really an issue in itself, but more like an aesthetic thing.

**Comment by BenPortner** [comment]
I can't find `Sm3` in my db. Is this a bug?

```python
import bw2data as bd
bd.projects.set_current("my_project")
{a["unit"] for a in bd.Database("cutoff391")}
Out[5]: 
{'cubic meter',
 'guest night',
 'hectare',
 'hour',
 'kg*day',
 'kilogram',
 'kilometer',
 'kilometer-year',
 'kilowatt hour',
 'litre',
 'megajoule',
 'meter',
 'meter-year',
 'person kilometer',
 'square meter',
 'square meter-year',
 'ton kilometer',
 'unit'}
```

**Comment by romainsacchi** [comment]
Strange. For "nylon 6 production, RoW", the output of "Gas, natural" is in "Sm3" in ei 39.
Can you confirm you have the correct unit for that flow (which I. guess should be "cubic meter")?

**Comment by romainsacchi** [comment]
I see the same in ei391.

**Comment by BenPortner** [comment]
That's the biosphere, then:

```python
{a["unit"] for a in bd.Database("biosphere3")}
Out[6]: 
{'EUR2005',
 'Sm3',
 'cubic meter',
 'cubic meter-year',
 'kilo Becquerel',
 'kilogram',
 'megajoule',
 'square meter',
 'square meter-year'}
```

**Comment by romainsacchi** [comment]
Yes, the biosphere for ei39 that comes with `bw2io 0.8.8`.

**Comment by BenPortner** [comment]
> Can you confirm you have the correct unit for that flow (which I. guess should be "cubic meter")?

I feel like we should avoid normalizing `Sm3` to `cubic meter`. This would lead to a loss of information, as `standard cubic meter` is more precise than just `cubic meter` (namely a cubic meter at standard pressure and standard temperature). As to renaming `Sm3` to something more descriptive like `standard cubic meter`, I am open. Same for `kg*day`. Any suggestions here @romainsacchi?

**Comment by romainsacchi** [comment]
I don't know. Unless I'm wrong, natural gas datasets, for example, refer to cubic meters in standard conditions and use the unit `cubic meter`. So, in several cases, `cubic meter` already signifies `Sm3`.
