### ISSUE TITLE
backup_project_directory doesn't return file path

### ISSUE THREAD

**Issue by HamedAkhavan** [brightway-lca/brightway2-io#179]
Hi,
the function [backup_project_directory](https://github.com/brightway-lca/brightway2-io/blob/61786c01141e81f29d5d6deb409f9029a17e1487/bw2io/backup.py#L28) is specified to have a return value of the created backup file path. but it's not returning anything.

**Comment by cmutel** [comment]
Fixed in 3b7fbb03c71d27b055e15c0398bffdb67ad15634
