### ISSUE TITLE
can't import bw2io

### ISSUE THREAD

**Issue by xiaoshir** [brightway-lca/brightway2-io#200]
```python
import bw2io as bi
```

Throws the error: 
```
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
Cell In[1], line 4
      2 import bw2data as bd
      3 import bw2calc as bc
----> 4 import bw2io as bi
      5 import matrix_utils as mu
      6 import bw_processing as bp

File C:\miniconda3_py37\envs\solarpv_new\Lib\site-packages\bw2io\__init__.py:95
     93 from .unlinked_data import unlinked_data, UnlinkedData
     94 from .utils import activity_hash, es2_activity_hash, load_json_data_file
---> 95 from .remote import install_project
     97 from bw2data import config, databases
     99 config.metadata.extend(
    100     [
    101         migrations,
    102         unlinked_data,
    103     ]
    104 )

File C:\miniconda3_py37\envs\solarpv_new\Lib\site-packages\bw2io\remote.py:25
     16 PROJECTS_BW25 = {
     17     "ecoinvent-3.8-biosphere": "ecoinvent-3.8-biosphere.tar.gz",
     18     "ecoinvent-3.9.1-biosphere": "ecoinvent-3.9.1-biosphere.tar.gz",
     19     "USEEIO-1.1": "USEEIO-1.1.tar.gz",
     20 }
     22 cache_dir = Path(
     23     user_data_dir(appname="bw2io-project-cache", appauthor="brightway-team")
     24 )
---> 25 cache_dir.mkdir(exist_ok=True)
     28 def get_projects(update_config: Optional[bool] = True) -> dict:
     29     BW2 = bd.__version__ < (4,)

File C:\miniconda3_py37\envs\solarpv_new\Lib\pathlib.py:1116, in Path.mkdir(self, mode, parents, exist_ok)
   1112 """
   1113 Create a new directory at this given path.
   1114 """
   1115 try:
-> 1116     os.mkdir(self, mode)
   1117 except FileNotFoundError:
   1118     if not parents or self.parent == self:

FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\zhang_x\\AppData\\Local\\brightway-team\\bw2io-project-cache'
```
The version of bw2io I have is `0.9.dev17`

**Comment by michaelweinold** [comment]
Please:

```pyton
conda install conda-tree
conda-tree depends -t brightway25
```

and paste the output below.

**Comment by xiaoshir** [comment]
│  │  ├─ voluptuous 0.13.1 [required: >=0.12]
  │  │  │  └─ python 3.11.3 [required: >=3.6]
  │  │  │     └─ dependencies of python displayed above
  │  │  ├─ whoosh 2.7.4 [required: any]
  │  │  │  └─ python 3.11.3 [required: any]
  │  │  │     └─ dependencies of python displayed above
  │  │  └─ wrapt 1.14.1 [required: >=1.12]
  │  │     ├─ python 3.11.3 [required: >=3.11,<3.12.0a0]
  │  │     │  └─ dependencies of python displayed above
  │  │     ├─ vc 14.2 [required: >=14.1,<15.0a0]
  │  │     │  └─ dependencies of vc displayed above
  │  │     └─ vs2015_runtime 14.34.31931 [required: >=14.16.27012,<15.0a0]
  │  │        └─ dependencies of vs2015_runtime displayed above
  │  ├─ matplotlib-base 3.7.1 [required: any]
  │  │  ├─ contourpy 1.0.5 [required: >=1.0.1]
  │  │  │  ├─ numpy 1.24.3 [required: >=1.16]
  │  │  │  │  └─ dependencies of numpy displayed above
  │  │  │  ├─ python 3.11.3 [required: >=3.11,<3.12.0a0]
  │  │  │  │  └─ dependencies of python displayed above
  │  │  │  ├─ vc 14.2 [required: >=14.1,<15.0a0]
  │  │  │  │  └─ dependencies of vc displayed above
  │  │  │  └─ vs2015_runtime 14.34.31931 [required: >=14.16.27012,<15.0a0]
  │  │  │     └─ dependencies of vs2015_runtime displayed above
  │  │  ├─ cycler 0.11.0 [required: >=0.10]
  │  │  │  └─ python 3.11.3 [required: >=3.6]
  │  │  │     └─ dependencies of python displayed above
  │  │  ├─ fonttools 4.25.0 [required: >=4.22.0]
  │  │  │  ├─ brotli 1.0.9 [required: >=1.0.1]
  │  │  │  │  ├─ brotli-bin 1.0.9 [required: 1.0.9, h2bbff1b_7]
  │  │  │  │  │  ├─ libbrotlidec 1.0.9 [required: 1.0.9, h2bbff1b_7]
  │  │  │  │  │  │  ├─ libbrotlicommon 1.0.9 [required: 1.0.9, h2bbff1b_7]
  │  │  │  │  │  │  │  ├─ vc 14.2 [required: >=14.1,<15.0a0]
  │  │  │  │  │  │  │  │  └─ dependencies of vc displayed above
  │  │  │  │  │  │  │  └─ vs2015_runtime 14.34.31931 [required: >=14.16.27012,<15.0a0]
  │  │  │  │  │  │  │     └─ dependencies of vs2015_runtime displayed above
  │  │  │  │  │  │  ├─ vc 14.2 [required: >=14.1,<15.0a0]
  │  │  │  │  │  │  │  └─ dependencies of vc displayed above
  │  │  │  │  │  │  └─ vs2015_runtime 14.34.31931 [required: >=14.16.27012,<15.0a0]
  │  │  │  │  │  │     └─ dependencies of vs2015_runtime displayed above
  │  │  │  │  │  ├─ libbrotlienc 1.0.9 [required: 1.0.9, h2bbff1b_7]
  │  │  │  │  │  │  ├─ libbrotlicommon 1.0.9 [required: 1.0.9, h2bbff1b_7]
  │  │  │  │  │  │  │  └─ dependencies of libbrotlicommon displayed above
  │  │  │  │  │  │  ├─ vc 14.2 [required: >=14.1,<15.0a0]
  │  │  │  │  │  │  │  └─ dependencies of vc displayed above
  │  │  │  │  │  │  └─ vs2015_runtime 14.34.31931 [required: >=14.16.27012,<15.0a0]
  │  │  │  │  │  │     └─ dependencies of vs2015_runtime displayed above
  │  │  │  │  │  ├─ vc 14.2 [required: >=14.1,<15.0a0]
  │  │  │  │  │  │  └─ dependencies of vc displayed above
  │  │  │  │  │  └─ vs2015_runtime 14.34.31931 [required: >=14.16.27012,<15.0a0]  │  │  │  │  │     └─ dependencies of vs2015_runtime displayed above
  │  │  │  │  ├─ libbrotlidec 1.0.9 [required: 1.0.9, h2bbff1b_7]
  │  │  │  │  │  └─ dependencies of libbrotlidec displayed above
  │  │  │  │  ├─ libbrotlienc 1.0.9 [required: 1.0.9, h2bbff1b_7]
  │  │  │  │  │  └─ dependencies of libbrotlienc displayed above
  │  │  │  │  ├─ vc 14.2 [required: >=14.1,<15.0a0]
  │  │  │  │  │  └─ dependencies of vc displayed above
  │  │  │  │  └─ vs2015_runtime 14.34.31931 [required: >=14.16.27012,<15.0a0]
  │  │  │  │     └─ dependencies of vs2015_runtime displayed above
  │  │  │  ├─ munkres 1.1.4 [required: any]
  │  │  │  │  └─ python 3.11.3 [required: any]
  │  │  │  │     └─ dependencies of python displayed above
  │  │  │  └─ python 3.11.3 [required: >=3.6]
  │  │  │     └─ dependencies of python displayed above
  │  │  ├─ freetype 2.12.1 [required: >=2.10.4,<3.0a0]
  │  │  │  ├─ libpng 1.6.39 [required: >=1.6.37,<1.7.0a0]
  │  │  │  │  ├─ vc 14.2 [required: >=14.1,<15.0a0]
  │  │  │  │  │  └─ dependencies of vc displayed above
  │  │  │  │  ├─ vs2015_runtime 14.34.31931 [required: >=14.16.27012,<15.0a0]
  │  │  │  │  │  └─ dependencies of vs2015_runtime displayed above
  │  │  │  │  └─ zlib 1.2.13 [required: >=1.2.13,<1.3.0a0]
  │  │  │  │     └─ dependencies of zlib displayed above
  │  │  │  ├─ vc 14.2 [required: >=14.1,<15.0a0]
  │  │  │  │  └─ dependencies of vc displayed above
  │  │  │  ├─ vs2015_runtime 14.34.31931 [required: >=14.16.27012,<15.0a0]
  │  │  │  │  └─ dependencies of vs2015_runtime displayed above
  │  │  │  └─ zlib 1.2.13 [required: >=1.2.13,<1.3.0a0]
  │  │  │     └─ dependencies of zlib displayed above
  │  │  ├─ kiwisolver 1.4.4 [required: >=1.0.1]
  │  │  │  ├─ python 3.11.3 [required: >=3.11,<3.12.0a0]
  │  │  │  │  └─ dependencies of python displayed above
  │  │  │  ├─ vc 14.2 [required: >=14.1,<15.0a0]
  │  │  │  │  └─ dependencies of vc displayed above
  │  │  │  └─ vs2015_runtime 14.34.31931 [required: >=14.16.27012,<15.0a0]
  │  │  │     └─ dependencies of vs2015_runtime displayed above
  │  │  ├─ numpy 1.24.3 [required: >=1.23.5,<2.0a0]
  │  │  │  └─ dependencies of numpy displayed above
  │  │  ├─ packaging 23.0 [required: >=20.0]
  │  │  │  └─ dependencies of packaging displayed above
  │  │  ├─ pillow 9.4.0 [required: >=6.2.0]
  │  │  │  ├─ freetype 2.12.1 [required: >=2.10.4,<3.0a0]
  │  │  │  │  └─ dependencies of freetype displayed above
  │  │  │  ├─ jpeg 9e [required: >=9e,<10a]
  │  │  │  │  ├─ vc 14.2 [required: >=14.1,<15.0a0]
  │  │  │  │  │  └─ dependencies of vc displayed above
  │  │  │  │  └─ vs2015_runtime 14.34.31931 [required: >=14.16.27012,<15.0a0]
  │  │  │  │     └─ dependencies of vs2015_runtime displayed above
  │  │  │  ├─ libtiff 4.5.0 [required: >=4.2.0,<5.0a0]
  │  │  │  │  ├─ jpeg 9e [required: >=9e,<10a]
  │  │  │  │  │  └─ dependencies of jpeg displayed above
  │  │  │  │  ├─ lerc 3.0 [required: >=3.0,<4.0a0]
  │  │  │  │  │  ├─ vc 14.2 [required: >=14.1,<15.0a0]
  │  │  │  │  │  │  └─ dependencies of vc displayed above
  │  │  │  │  │  └─ vs2015_runtime 14.34.31931 [required: >=14.16.27012,<15.0a0]  │  │  │  │  │     └─ dependencies of vs2015_runtime displayed above
  │  │  │  │  ├─ libdeflate 1.17 [required: >=1.17,<1.18.0a0]
  │  │  │  │  │  ├─ vc 14.2 [required: >=14.1,<15.0a0]
  │  │  │  │  │  │  └─ dependencies of vc displayed above
  │  │  │  │  │  └─ vs2015_runtime 14.34.31931 [required: >=14.16.27012,<15.0a0]  │  │  │  │  │     └─ dependencies of vs2015_runtime displayed above
  │  │  │  │  ├─ vc 14.2 [required: >=14.1,<15.0a0]
  │  │  │  │  │  └─ dependencies of vc displayed above
  │  │  │  │  ├─ vs2015_runtime 14.34.31931 [required: >=14.16.27012,<15.0a0]
  │  │  │  │  │  └─ dependencies of vs2015_runtime displayed above
  │  │  │  │  ├─ xz 5.4.2 [required: >=5.2.4,<6.0a0]
  │  │  │  │  │  └─ dependencies of xz displayed above
  │  │  │  │  ├─ zlib 1.2.13 [required: >=1.2.13,<1.3.0a0]
  │  │  │  │  │  └─ dependencies of zlib displayed above
  │  │  │  │  └─ zstd 1.5.5 [required: >=1.5.2,<1.6.0a0]
  │  │  │  │     ├─ lz4-c 1.9.4 [required: >=1.9.4,<1.10.0a0]
  │  │  │  │     │  ├─ vc 14.2 [required: >=14.1,<15.0a0]
  │  │  │  │     │  │  └─ dependencies of vc displayed above
  │  │  │  │     │  └─ vs2015_runtime 14.34.31931 [required: >=14.16.27012,<15.0a0]
  │  │  │  │     │     └─ dependencies of vs2015_runtime displayed above
  │  │  │  │     ├─ vc 14.2 [required: >=14.1,<15.0a0]
  │  │  │  │     │  └─ dependencies of vc displayed above
  │  │  │  │     ├─ vs2015_runtime 14.34.31931 [required: >=14.16.27012,<15.0a0]  │  │  │  │     │  └─ dependencies of vs2015_runtime displayed above
  │  │  │  │     ├─ xz 5.4.2 [required: >=5.2.10,<6.0a0]
  │  │  │  │     │  └─ dependencies of xz displayed above
  │  │  │  │     └─ zlib 1.2.13 [required: >=1.2.13,<1.3.0a0]
  │  │  │  │        └─ dependencies of zlib displayed above
  │  │  │  ├─ libwebp 1.2.4 [required: >=1.2.0,<1.3.0a0]
  │  │  │  │  ├─ giflib 5.2.1 [required: >=5.2.1,<5.3.0a0]
  │  │  │  │  │  ├─ vc 14.2 [required: >=14.1,<15.0a0]
  │  │  │  │  │  │  └─ dependencies of vc displayed above
  │  │  │  │  │  └─ vs2015_runtime 14.34.31931 [required: >=14.16.27012,<15.0a0]  │  │  │  │  │     └─ dependencies of vs2015_runtime displayed above
  │  │  │  │  ├─ jpeg 9e [required: >=9e,<10a]
  │  │  │  │  │  └─ dependencies of jpeg displayed above
  │  │  │  │  ├─ libpng 1.6.39 [required: >=1.6.37,<1.7.0a0]
  │  │  │  │  │  └─ dependencies of libpng displayed above
  │  │  │  │  ├─ libtiff 4.5.0 [required: >=4.1.0,<5.0a0]
  │  │  │  │  │  └─ dependencies of libtiff displayed above
  │  │  │  │  ├─ libwebp-base 1.2.4 [required: 1.2.4.*]
  │  │  │  │  │  ├─ vc 14.2 [required: >=14.1,<15.0a0]
  │  │  │  │  │  │  └─ dependencies of vc displayed above
  │  │  │  │  │  └─ vs2015_runtime 14.34.31931 [required: >=14.16.27012,<15.0a0]  │  │  │  │  │     └─ dependencies of vs2015_runtime displayed above
  │  │  │  │  ├─ vc 14.2 [required: >=14.1,<15.0a0]
  │  │  │  │  │  └─ dependencies of vc displayed above
  │  │  │  │  └─ vs2015_runtime 14.34.31931 [required: >=14.16.27012,<15.0a0]
  │  │  │  │     └─ dependencies of vs2015_runtime displayed above
  │  │  │  ├─ python 3.11.3 [required: >=3.11,<3.12.0a0]
  │  │  │  │  └─ dependencies of python displayed above
  │  │  │  ├─ tk 8.6.12 [required: >=8.6.12,<8.7.0a0]
  │  │  │  │  └─ dependencies of tk displayed above
  │  │  │  ├─ vc 14.2 [required: >=14.1,<15.0a0]
  │  │  │  │  └─ dependencies of vc displayed above
  │  │  │  ├─ vs2015_runtime 14.34.31931 [required: >=14.16.27012,<15.0a0]
  │  │  │  │  └─ dependencies of vs2015_runtime displayed above
  │  │  │  └─ zlib 1.2.13 [required: >=1.2.13,<1.3.0a0]
  │  │  │     └─ dependencies of zlib displayed above
  │  │  ├─ pyparsing 3.0.9 [required: >=2.3.1]
  │  │  │  └─ python 3.11.3 [required: >=3.11,<3.12.0a0]
  │  │  │     └─ dependencies of python displayed above
  │  │  ├─ python 3.11.3 [required: >=3.11,<3.12.0a0]
  │  │  │  └─ dependencies of python displayed above
  │  │  ├─ python-dateutil 2.8.2 [required: >=2.7]
  │  │  │  └─ dependencies of python-dateutil displayed above
  │  │  ├─ vc 14.2 [required: >=14.1,<15.0a0]
  │  │  │  └─ dependencies of vc displayed above
  │  │  └─ vs2015_runtime 14.34.31931 [required: >=14.16.27012,<15.0a0]
  │  │     └─ dependencies of vs2015_runtime displayed above
  │  ├─ numpy 1.24.3 [required: any]
  │  │  └─ dependencies of numpy displayed above
  │  ├─ pandas 1.5.3 [required: any]
  │  │  └─ dependencies of pandas displayed above
  │  ├─ pyprind 2.11.2 [required: any]
  │  │  └─ dependencies of pyprind displayed above
  │  ├─ python 3.11.3 [required: any]
  │  │  └─ dependencies of python displayed above
  │  ├─ requests 2.29.0 [required: any]
  │  │  └─ dependencies of requests displayed above
  │  ├─ scipy 1.10.1 [required: any]
  │  │  └─ dependencies of scipy displayed above
  │  ├─ stats_arrays 0.6.5 [required: any]
  │  │  └─ dependencies of stats_arrays displayed above
  │  └─ tabulate 0.8.10 [required: any]
  │     └─ python 3.11.3 [required: >=3.11,<3.12.0a0]
  │        └─ dependencies of python displayed above
  ├─ bw2calc 2.0.dev13 [required: >=2.0.dev12]
  │  └─ dependencies of bw2calc displayed above
  ├─ bw2data 4.0.dev18 [required: >=4.0.dev18]
  │  └─ dependencies of bw2data displayed above
  ├─ bw2io 0.9.dev17 [required: >=0.9.dev10]
  │  ├─ astunparse 1.6.3 [required: >=1.6.1]
  │  │  └─ dependencies of astunparse displayed above
  │  ├─ bw2calc 2.0.dev13 [required: >=2.0.dev12]
  │  │  └─ dependencies of bw2calc displayed above
  │  ├─ bw2data 4.0.dev18 [required: >=4.0.dev17]
  │  │  └─ dependencies of bw2data displayed above
  │  ├─ bw_migrations 0.1 [required: any]
  │  │  ├─ python 3.11.3 [required: any]
  │  │  │  └─ dependencies of python displayed above
  │  │  └─ stats_arrays 0.6.5 [required: any]
  │  │     └─ dependencies of stats_arrays displayed above
  │  ├─ bw_processing 0.8.2 [required: any]
  │  │  └─ dependencies of bw_processing displayed above
  │  ├─ lxml 4.9.2 [required: any]
  │  │  └─ dependencies of lxml displayed above
  │  ├─ mrio_common_metadata 0.2.1 [required: any]
  │  │  ├─ openpyxl 3.0.10 [required: any]
  │  │  │  ├─ et_xmlfile 1.1.0 [required: any]
  │  │  │  │  └─ python 3.11.3 [required: >=3.11,<3.12.0a0]
  │  │  │  │     └─ dependencies of python displayed above
  │  │  │  ├─ python 3.11.3 [required: >=3.11,<3.12.0a0]
  │  │  │  │  └─ dependencies of python displayed above
  │  │  │  ├─ vc 14.2 [required: >=14.1,<15.0a0]
  │  │  │  │  └─ dependencies of vc displayed above
  │  │  │  └─ vs2015_runtime 14.34.31931 [required: >=14.16.27012,<15.0a0]
  │  │  │     └─ dependencies of vs2015_runtime displayed above
  │  │  ├─ pandas 1.5.3 [required: any]
  │  │  │  └─ dependencies of pandas displayed above
  │  │  ├─ python 3.11.3 [required: any]
  │  │  │  └─ dependencies of python displayed above
  │  │  ├─ pyxlsb 1.0.10 [required: any]
  │  │  │  └─ python 3.11.3 [required: >=3.6]
  │  │  │     └─ dependencies of python displayed above
  │  │  ├─ scipy 1.10.1 [required: any]
  │  │  │  └─ dependencies of scipy displayed above
  │  │  └─ xlrd 2.0.1 [required: any]
  │  │     └─ python 3.11.3 [required: any]
  │  │        └─ dependencies of python displayed above
  │  ├─ numpy 1.24.3 [required: >=1.20]
  │  │  └─ dependencies of numpy displayed above
  │  ├─ openpyxl 3.0.10 [required: any]
  │  │  └─ dependencies of openpyxl displayed above
  │  ├─ platformdirs 2.5.2 [required: any]
  │  │  └─ python 3.11.3 [required: >=3.11,<3.12.0a0]
  │  │     └─ dependencies of python displayed above
  │  ├─ psutil 5.9.0 [required: any]
  │  │  └─ dependencies of psutil displayed above
  │  ├─ pyprind 2.11.2 [required: any]
  │  │  └─ dependencies of pyprind displayed above
  │  ├─ python 3.11.3 [required: >=3.9]
  │  │  └─ dependencies of python displayed above
  │  ├─ scipy 1.10.1 [required: any]
  │  │  └─ dependencies of scipy displayed above
  │  ├─ stats_arrays 0.6.5 [required: >=0.6.5]
  │  │  └─ dependencies of stats_arrays displayed above
  │  ├─ tqdm 4.65.0 [required: any]
  │  │  └─ dependencies of tqdm displayed above
  │  ├─ unidecode 1.2.0 [required: any]
  │  │  └─ python 3.11.3 [required: 2.7|>=3.5]
  │  │     └─ dependencies of python displayed above
  │  ├─ voluptuous 0.13.1 [required: any]
  │  │  └─ dependencies of voluptuous displayed above
  │  ├─ xlrd 2.0.1 [required: any]
  │  │  └─ dependencies of xlrd displayed above
  │  └─ xlsxwriter 3.1.1 [required: any]
  │     └─ python 3.11.3 [required: >=3.11,<3.12.0a0]
  │        └─ dependencies of python displayed above
  ├─ bw_migrations 0.1 [required: any]
  │  └─ dependencies of bw_migrations displayed above
  ├─ bw_processing 0.8.2 [required: >=0.8.2]
  │  └─ dependencies of bw_processing displayed above
  ├─ libblas 3.9.0 [required: *, *mkl]
  │  └─ mkl 2021.4.0 [required: 2021.4.0, h0e2418a_729]
  │     └─ dependencies of mkl displayed above
  ├─ matrix_utils 0.2.5 [required: >=0.2.5]
  │  └─ dependencies of matrix_utils displayed above
  ├─ mrio_common_metadata 0.2.1 [required: any]
  │  └─ dependencies of mrio_common_metadata displayed above
  ├─ numpy 1.24.3 [required: any]
  │  └─ dependencies of numpy displayed above
  ├─ pypardiso 0.4.2 [required: any]
  │  ├─ mkl 2021.4.0 [required: any]
  │  │  └─ dependencies of mkl displayed above
  │  ├─ numpy 1.24.3 [required: any]
  │  │  └─ dependencies of numpy displayed above
  │  ├─ python 3.11.3 [required: any]
  │  │  └─ dependencies of python displayed above
  │  └─ scipy 1.10.1 [required: any]
  │     └─ dependencies of scipy displayed above
  ├─ python 3.11.3 [required: >=3.9]
  │  └─ dependencies of python displayed above
  └─ stats_arrays 0.6.5 [required: >=0.6.5]
     └─ dependencies of stats_arrays displayed above

For the sake of clarity, some redundancies have been hidden.
Please use the '--full' option to display them anyway.

If you are tired of seeing 'conda' and 'python' everywhere,
you can use the '--small' option to hide their dependencies completely.

**Comment by michaelweinold** [comment]
It seems that [`cache_dir.mkdir(exist_ok=True, parents=True)`](https://github.com/brightway-lca/brightway2-io/blob/0c3c7288a897f57511ce17a6be1698e2cb9b08a1/bw2io/remote.py#L25), which calls [`Path.mkdir`](https://docs.python.org/3/library/pathlib.html#pathlib.Path.mkdir) does not work properly on Windows. Could you test this on a Windows machine, @romainsacchi?
