### ISSUE TITLE
Download of Agribalyse 

### ISSUE THREAD

**Issue by SamiraHuber** [brightway-lca/brightway2-io#225]
On your documentation (https://doc.agribalyse.fr/documentation-en/agribalyse-data/data-access) there is a link to download the Agribalyse database from Brightway:

<img width="777" alt="Bildschirmfoto 2023-10-13 um 23 53 19" src="https://github.com/brightway-lca/brightway2-io/assets/57727819/25e149b1-9d1f-4caa-ae46-4f89bfc1be76">

But the link when clicking on Brightway is giving me a "DNS_PROBE_FINISHED_NXDOMAIN"-Error

<img width="1037" alt="Bildschirmfoto 2023-10-13 um 23 55 17" src="https://github.com/brightway-lca/brightway2-io/assets/57727819/6b7d0f12-4ab4-43b9-8852-b2b14758c315">

**Comment by tngTUDOR** [comment]
There was a change in the way the documentation is structure. We now only have one page, with a drop down menu to swithc between bw25 and bw2(legacy) documentation:

https://docs.brightway.dev/en/latest/

![image](https://github.com/brightway-lca/brightway2-io/assets/10451451/78c46f31-bd61-40e4-b977-ed8f209c9b4f)
