### ISSUE TITLE
[QUESTION] Export database as bw2package file extension

### ISSUE THREAD

**Issue by alyabolowich** [brightway-lca/brightway2-io#226]
Hello,

When using the AB, I can export my db with the file extension bw2package. This is not possible in bw2io (only excel, csv, gefx, and matlab are supported to my knowledge). Is there a reason behind this? 

Thank you!

P.S. I couldn't add a label, but it should be considered a "question".

**Comment by cmutel** [comment]
The `bw2package` functionality actually comes from `bw2io`: https://github.com/brightway-lca/brightway2-io/blob/bw2legacy/bw2io/package.py

**Comment by alyabolowich** [comment]
Ah, great I missed that! Thank you!
