### ISSUE TITLE
[BW2 Legacy] Using older versions of Biosphere

### ISSUE THREAD

**Issue by marc-vdm** [brightway-lca/brightway2-io#230]
Some of our users (e.g. people in https://github.com/LCA-ActivityBrowser/activity-browser/issues/1137 and myself) still want (or have to) to create new projects for older versions of ecoinvent. I decided I wanted to add this functionality for AB (https://github.com/LCA-ActivityBrowser/activity-browser/issues/1142)

While Ab by uses 
https://github.com/brightway-lca/brightway2-io/blob/b19fae87ced639d0d8f5e700ab00125347c61040/bw2io/__init__.py#L99

This doesn't allow for specifying a version of biosphere to use. I decided to try to directly call the below instead
https://github.com/brightway-lca/brightway2-io/blob/b19fae87ced639d0d8f5e700ab00125347c61040/bw2io/importers/ecospold2_biosphere.py#L16-L19

However, I have now found that `bw2io` versions are only shipped with 1 (newest) version of biosphere. While I understand that these files will take up quite some space if supplied for each version -though note that the zips take only ~300kb- , the `version="3.9"` argument now doesn't make sense as no other version can be chosen.

I still want to help our users install the biosphere versions they need. Do you have suggestions how I can do this with `bw2io` code, or should I write my own function and provide my own data through AB?

**Comment by cmutel** [comment]
@marc-vdm The data format for biosphere flows has stayed the same for quite a while. I think it one wants both ecoinvent metadata *and* data they should use the now built-in ecoinvent functionality; however, I think it would be fine to bundle all biosphere flow lists for 3.6+ in one zip archive (to get maximum compression), and rewrite or add to the import code.

**Comment by marc-vdm** [comment]
I think this doesn't require action anymore. I've written a solution (https://github.com/LCA-ActivityBrowser/activity-browser/pull/1145) for AB for now. 

Once AB supports BW25, we don't need to worry about this anymore at all right?
