### ISSUE TITLE
Backport fix for "chemical formulas" from 0.9.DEV7 to 0.8.X ?

### ISSUE THREAD

**Issue by raphaeljolivet** [brightway-lca/brightway2-io#247]
Hi, 

Could you please backport this fix from 0.9.DEV7 to 0.8.X ?
*Change label for chemical formulas in ecospold2 import from formula to chemical formula*

This [impacts computation in lca_algebraic](https://github.com/oie-mines-paristech/lca_algebraic/issues/44)

**Comment by tngTUDOR** [comment]
@raphaeljolivet , it looks like the fix was merged, can we close this issue?
