### ISSUE TITLE
Need SimaPro migration for ecoinvent 3.2 names

### ISSUE THREAD

**Issue by aleksandra-kim** [brightway-lca/brightway2-io#26]
**[Original report](https://bitbucket.org/cmutel/brightway2-io/issue/26) by Chris Mutel (Bitbucket: [cmutel](https://bitbucket.org/cmutel), GitHub: [cmutel](https://github.com/cmutel)).**

----------------------------------------

**Comment by PascalLesage** [comment]
Migrations exist for 3.1 through 3.4.
