### ISSUE TITLE
Unlinked exchanges in EcoInvent 3.10

### ISSUE THREAD

**Issue by KellyC-IBP** [brightway-lca/brightway2-io#267]
Hi,
I imported EcoInvent 3.10 database, and there are quite a lot of unlinked exchanges as shown in the screenshot.
I went through the forum and got that the solution is to have a newer version of bw2io.

I made sure that I am have all the updates for Brightway2.5 installed

Is there another straight forward way to solve this problem?

Thanks
 
![image](https://github.com/user-attachments/assets/ec20aa2f-3764-4cdf-a6c4-343a365e0186)

**Comment by KellyC-IBP** [comment]
I have already installed the ecoinvent_interface prior to running the code above for importing EcoInvent 3.10
https://github.com/brightway-lca/brightway2-io/issues/231#issuecomment-2024860457

**Comment by KellyC-IBP** [comment]
Update:
After double checking, I realized I installed Brightway2 then followed the instructions for Brightway 2.5

**Comment by Haitham-ghaida** [comment]
Hi Kelly, I don't think just installing ecoinvent_interface does anything, you need to use it.

```python
bd.projects.set_current("FILL")
bi.import_ecoinvent_release(version="3.10", system_model="cutoff", username=(username="FILL",password="FILL")
```

Of course, if you don't have access to an ecoinvent account or the proper licence, I guess this doesn't help you.

**Comment by tngTUDOR** [comment]
hi @KellyC-IBP,
I think the issue you describe is solved by applying the comment you referenced 
( https://github.com/brightway-lca/brightway2-io/issues/231#issuecomment-2024860457 )
So, if you need more asistance, you can also reach-out to the bw mailing list.

I'm closing this issue, because it has a solution.
