### ISSUE TITLE
bw2io requires bw2parameters>=1.1.0 but only version 0.7 is available in conda

### ISSUE THREAD

**Issue by mfastudillo** [brightway-lca/brightway2-io#268]
Now importing bw2io returns an import error. It cannot find `Interpreter` from bw2parameters. This is probably something added in the latest updates of bw2parameters. Indeed bw2io [requires](https://github.com/brightway-lca/brightway2-io/blob/main/pyproject.toml) bw2parameters>=1.1.0 but only version 0.7 is available in [conda](https://anaconda.org/cmutel/bw2parameters) in the @cmutel channel

this is probably related to the contributions to the simapro importer,

releasing the new bw2parameters version in conda should solve the issue

**Comment by cmutel** [comment]
Recent `bw2parameters` versions are available on the `conda-forge` channel: https://anaconda.org/conda-forge/bw2parameters. In general `conda-forge` should have priority over individual channels 😄

**Comment by mfastudillo** [comment]
ah ok! sorry for that
