### ISSUE TITLE
Exchange Extractor for Ecospold2 only extracts CPC classification

### ISSUE THREAD

**Issue by tngTUDOR** [brightway-lca/brightway2-io#282]
# Current

the ecospold2 exchange extractor only parses the CPC classification

# Expected

ecoinvent 3.10 seems to have a more "detailed" HS2017 classification besides the CPC classification as well for the intermediary exchanges and the ecospold2 exchange extractor should honor it

https://github.com/brightway-lca/brightway2-io/blob/main/bw2io/extractors/ecospold2.py#L563

**Comment by adrien-perello** [comment]
The fix does not seem to address the issue, see #293
