### ISSUE TITLE
'verbs' and 'migrate_nodes' keywords not defined in current version

### ISSUE THREAD

**Issue by FRaymand** [brightway-lca/brightway2-io#285]
Greetings!
When running the agribalyse partial import notebook (from the recent Brightcon 2024), I get an error that verbs and migrate_nodes are not defined for the randonneur function (I remember it happened at the conference as well but I don't think it was addressed then). I'm not sure if this is an issue for bw2io or randonneur though.
![Screenshot 2024-10-04 131607](https://github.com/user-attachments/assets/1e3755aa-e093-4d3c-9ce7-08435f0c82e4)

**Comment by cmutel** [comment]
Please update your `bw2io` version.
