### ISSUE TITLE
bw2io has ''unidecode' as dependency, but it is never used.

### ISSUE THREAD

**Issue by tyrael147** [brightway-lca/brightway2-io#290]
While checking the dependencies of my package that leverages bw2io [0.9.dev41], I noticed that `unidecode` is installed by bw2io, but it is not imported by any bw module [see here](https://github.com/brightway-lca/brightway2-io/blame/2c0b3a0fd827f9a20b978fbc8ad8704a55297b3c/pyproject.toml#L56). My issue with `unidecode` is that it has a GPL license, which would require me to make my package GPL as well. I wonder if this dependency is there for a reason.

**Comment by cmutel** [comment]
Fixed in aea438e03754bd8169dc07c60bf741604a9d7e67
