### ISSUE TITLE
Two inventory.csv files in simapro fixture

### ISSUE THREAD

**Issue by BenPortner** [brightway-lca/brightway2-io#71]
When cloning bw-io, I get a warning:

```
warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:

  'tests/fixtures/simapro/inventory.CSV'
  'tests/fixtures/simapro/inventory.csv'

```

The two files look identical to me. Is there a special reason why there are two?

**Comment by cmutel** [comment]
@BenPortner Can you submit a PR deleting `inventory.CSV`? My system is in the middle of a big change, and I don't want to deal with changing it back and forth.

**Comment by BenPortner** [comment]
I deleted it, although I accidentally commited directly to the brightway-lca/brightway2-io@master branch. Apologies! If you want, I'll create a reverse commit and go the proper PR route. Let me know.

**Comment by cmutel** [comment]
That's fine ;) No need to make life complicated when it can be simple.
