### ISSUE TITLE
dependency on 'safe_filename' from 'bw_processing' causes import error

### ISSUE THREAD

**Issue by PascalLesage** [brightway-lca/brightway2-io#78]
I'm trying to contribute to `bw2io` (add SimaPro 3.4 and 3.5 mappings).
I followed the following steps: 
- forked from https://github.com/brightway-lca/brightway2-io.git
- created a conda environment and installed brightway2 as per https://2.docs.brightway.dev/installation.html
- I `pip install -e brightway2-io` 

All this seems to work as normal, but unfortunately, a [May 26 commit](https://github.com/brightway-lca/brightway2-io/commit/aee19f2514385c5f22825268731eb2f16290b1a7) has added a dependency to bw_processing and is preventing me from importing `bw2io`.

**Comment by PascalLesage** [comment]
Of course, the obvious workaround (that works well) is to clone and install the latest version of `bw_processing`.

**Comment by PascalLesage** [comment]
And while the fix works on one's computer, automatic testing on github fails when submitting a PR.

**Comment by cmutel** [comment]
Fixed. 0.8 release is on the legacy branch, with no bw_processing dependency, while bw_processing is explicitly a dependency on development branch.
