### ISSUE TITLE
Problem importing Ecoinvent database - Assertion error

### ISSUE THREAD

**Issue by sg2219** [brightway-lca/brightway2-io#87]
Hello Everyone,

I have a problem importing ecoinvent database in brightway2. I have attached a screenshot for the reference. Please let me know how I can proceed further.

Thank you!
![image](https://user-images.githubusercontent.com/77126765/104569021-133c7100-5651-11eb-823a-0c7382210dc5.png)

**Comment by BenPortner** [comment]
Dear @sg2219,
The error message indicates that the path you specified for the datasets does not exist. You probably have to specify the full path without ~.
Cheers.
Ben

**Comment by sg2219** [comment]
Hello Ben,
Thank you for the quick reply. It worked when I specified full path. 
regards,
Swathi
