### ISSUE TITLE
AssertionError: Can't find migration biosphere-2-3-categories

### ISSUE THREAD

**Issue by sg2219** [brightway-lca/brightway2-io#88]
Hello all,

I am trying to import an excel database(xlsx format) and I am getting an assertion error (attached a screenshot for your reference). Could you please take a look and let me know how I have to proceed further?

Thank you
![image](https://user-images.githubusercontent.com/77126765/104897091-4005c680-5978-11eb-9ff4-ba2c79c19e02.png)

**Comment by BenPortner** [comment]
Did you perform `bw.bw2setup()`?

**Comment by sg2219** [comment]
yes, I did.

**Comment by BenPortner** [comment]
Is this the only migration that fails? Can you check if the other migrations are existent?

**Comment by sg2219** [comment]
Thank you.
It worked now after I tried the same with a new project. I wonder why it did not work with the old project though.

**Comment by BenPortner** [comment]
Sounds like unexpected data loss. Did you delete files from the bw folder? Let me know if you find the reason. I will close this for now.

**Comment by CHarpprecht** [comment]
I had the same problem today, and switching to a new project helped as well :)
