### ISSUE TITLE
Unsupported pickle protocol:5 when importing brightway2

### ISSUE THREAD

**Issue by sg2219** [brightway-lca/brightway2-io#90]
Hello all,

I installed miniconda3 today and I am getting an error when I try importing brightway2. Please find more info in the screenshot attached. Could you please check and help with the same.

Thank you.
![Screenshot 2021-02-12 at 13 40 25](https://user-images.githubusercontent.com/77126765/107769557-78f74800-6d38-11eb-9424-6ec7f995939c.png)
![Screenshot 2021-02-12 at 13 40 38](https://user-images.githubusercontent.com/77126765/107769576-7e549280-6d38-11eb-8498-52d1e4ea27df.png)

**Comment by cmutel** [comment]
Python 3.8 introduced a new pickle protocol, [version 5](https://www.python.org/dev/peps/pep-0574/). At some point, you ran
3.8, and Brightway saved some data in this format.

Although this incompatibility was noted in the Brightway2 updates mailing list, this is a bug that has bitten more people than you!

You now have a few options:

* The easiest: Run everything using Python 3.8. All Brightway libraries should still function fine.
* Delete the projects that use this pickle version.
* Use the development version of `bw2data`. The development version of `bw2data` uses the [older pickle format](https://github.com/brightway-lca/brightway2-data/commit/09f13b22e651e0d496f0eff63ef984c4e8ea637d). However, this could have [other bugs](https://brightway.groups.io/g/development/message/76).
