### ISSUE TITLE
LCIA method importer

### ISSUE THREAD

**Issue by bsteubing** [brightway-lca/brightway2-io#91]
I have been asked several times recently if the Activity Browser could import new LCIA methods. Data was available, e.g., in the ecospold1 format, but probably also as simple Excel files. I have no specific preference on data format at this moment, but it would be great to have an LCIA method import function, just like we can import databases... it could be as simple as being an Excel file that has columns to identify the environmental flows and then additional column(s) with the characterization factors. If this becomes available in brightway, we'd happily implement the UI for that in the AB.

**Comment by cmutel** [comment]
Fixed in 0.8 release.

**Comment by cardosan** [comment]
I am trying to modify some IA methods by:

- exporting their data in a format importable from `bw2io.ExcelLCIAImporter `
- changing what I need
- reimporting with `bw2io.ExcelLCIAImporter `


but some methods have multiple units such as the followings 
```

 {'kilogram', 'cubic meter'} units in ('ILCD 2.0 2018 midpoint', 'resources', 'fossils')
 {'square meter', 'square meter-year'} units in ('ILCD 2.0 2018 midpoint', 'resources', 'land use')
 {'kilogram', 'cubic meter'} units in ('ILCD 2.0 2018 midpoint no LT', 'resources', 'fossils')
, {'square meter', 'square meter-year'} units in ('ILCD 2.0 2018 midpoint no LT', 'resources', 'land use')
```

How can the function be used in these cases (if)?

**Comment by ar-ali** [comment]
Hi.

Is this feature available in AB?

**Comment by bsteubing** [comment]
good, question, I have not followed up what the changes in v0.8 mentioned by @cmutel actually mean in terms of possibilities for the AB. Currently, this feature is still lacking in the AB, but if it works at the BW level it should be more or less trivial to implement at the AB level and then I would say this is something of priority @marc-vdm and could be implemented by Pim perhaps?

**Comment by marc-vdm** [comment]
Tagging @joeytje50 for reference
