### ISSUE TITLE
Methods dictionary with 0 objects

### ISSUE THREAD

**Issue by songkuku** [brightway-lca/brightway2-io#95]
Hello,
I've been following the tutorial and I have an issue regarding 'bw.bw2setup'.
After installing Biosphere3, there comes an error 'Excel xlsx file; not supported' during the LCIA methods installation.
I think something goes wrong with the 'xlrd' package, and it says it no longer supports anything other than '.xls'. The file in the tutorial is '.xlsx', therefore I guess we need to use the package 'openpyxl'. 
Have you maybe encountered the same error?
Thank you (:

**Comment by BenPortner** [comment]
Hello @songkuku,

the issue is known and a quick fix is described here: https://github.com/brightway-lca/brightway2/issues/21.

Cheers.
Ben
